apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ppw9xoouw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ppw9xoouw-python 
  name: ppw9xoouw-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ppw9xoouw-python 
